### ISSUE TITLE
heatmap cut vs cuts

### ISSUE THREAD

**Issue by magsreed** [spice-herald/detanalysis#4]
https://github.com/spice-herald/detanalysis/blob/668e37d1d526c08df7e416a1b190b16e3499014e/detanalysis/analyzer.py#L956C1-L956C1

Heatmap functionality references cuts as `cut=`, but other plot functionalities use `cuts=`

**Comment by serfass** [comment]
The analyzer's heatmap function doesn't currently display data from multiple cuts like the other plot functions such as "hist". Rather you can give a  "cut"  argument and data will be displayed after cut.  So the argument "cut" in heatmap is different than "cuts", which can a list of cuts such as [None, cut1, cut2].

**Comment by magsreed** [comment]
Ok this makes sense, heatmap does display a grayed out version of the cut data, if you pass something like 'include_previous_cuts=True' but yes it doesn't show by color or which cut is which.
